<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="NetDriver">
      <HintPath>lib/NetDriver.dll</HintPath>
    </Reference>
    <Reference Include="AVcontrol">
      <HintPath>lib/AVcontrol.dll</HintPath>
    </Reference>
    <Reference Include="JabrAPI">
      <HintPath>lib/JabrAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
  </ItemGroup>

</Project>
