<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

   <ItemGroup>
    <Reference Include="AVcontrol">
      <HintPath>..\lib\AVcontrol\Preview\AVcontrol.dll</HintPath>
    </Reference>
    <Reference Include="NetDriver">
      <HintPath>../../ReMessenger\lib/NetDriver/NetDriver.dll</HintPath>
    </Reference>
    <Reference Include="JabrAPI">
      <HintPath>..\..\ReMessenger/lib/JabrAPI/Preview/21.07 New extended only new camouflage/JabrAPI.dll</HintPath>
    </Reference>
    <Reference Include="Shared">
      <HintPath>..\lib\Shared\Shared.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
