<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AVcontrol">
      <HintPath>..\lib\AVcontrol\Preview\AVcontrol.dll</HintPath>
    </Reference>
    <Reference Include="JabrAPI">
      <HintPath>..\lib\JabrAPI\v5.0.1\JabrAPI.dll</HintPath>
    </Reference>
    <Reference Include="NetDriver">
      <HintPath>../lib/NetDriver/NetDriver.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>
</Project>
